apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: turanoguzhan/k8s-example:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.properties"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: demo-config