apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-svc
spec:
  selector:
    app: demo
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30088
  type: NodePort
