spring.application.name=k8sexample

greeting=Welcome
message=Catch me, if you can. (possibly you can but it worths to try.)


management.health.probes.enabled=true
management.endpoints.web.exposure.include=health
